// ============================================================
// Top 181 US home-buying metros
// Audited 2026-09-08. Replaces a prior version that cited
// "NAR, Zillow, Tax Foundation, Census ACS" as sources for 2024
// data but was never actually pulled from them - round, unsourced
// placeholder figures (e.g. New York flat $750,000, Los Angeles flat
// $850,000).
//
// Real sources, all downloaded and matched directly:
//   - medianHomePrice, medianHouseholdIncome: reused from the
//     networthrank.com city-data.ts audit (2026-09-04), since both
//     sites cover the identical 181 (city, state) pairs. Real Zillow
//     Home Value Index (ZHVI), July 2026, for home prices; real HUD
//     FY2026 Section 8 Income Limits median family income for the
//     income proxy.
//   - propertyTaxRate: real state-level effective property tax rate,
//     Tax Foundation, "Property Taxes by State and County, 2026"
//     (https://taxfoundation.org/data/all/state/property-taxes-by-state-county/),
//     2024 ACS 5-year estimate (the real, current vintage for this
//     dataset - effective property tax rates are published on a lag
//     since they're derived from Census ACS 5-year data, not an
//     annually-reset rate table). This is a state-level rate applied
//     per city, not a city-specific rate - a real, disclosed
//     simplification, same pattern as netpaytool's STATE_TAX_RATES.
// ============================================================

export interface CityData {
  name: string;
  state: string;
  stateCode: string;
  medianHomePrice: number;
  propertyTaxRate: number;   // annual, decimal (e.g. 0.0172 = 1.72%)
  medianHouseholdIncome: number;
}

export const CITY_DATA: Record<string, CityData> = {
  "houston": {
    name: "Houston",
    state: "Texas",
    stateCode: "TX",
    medianHomePrice: 307_800,
    propertyTaxRate: 0.014,
    medianHouseholdIncome: 104_000,
  },
  "san-antonio": {
    name: "San Antonio",
    state: "Texas",
    stateCode: "TX",
    medianHomePrice: 279_400,
    propertyTaxRate: 0.014,
    medianHouseholdIncome: 100_600,
  },
  "dallas": {
    name: "Dallas",
    state: "Texas",
    stateCode: "TX",
    medianHomePrice: 364_800,
    propertyTaxRate: 0.014,
    medianHouseholdIncome: 121_100,
  },
  "austin": {
    name: "Austin",
    state: "Texas",
    stateCode: "TX",
    medianHomePrice: 424_300,
    propertyTaxRate: 0.014,
    medianHouseholdIncome: 134_400,
  },
  "fort-worth": {
    name: "Fort Worth",
    state: "Texas",
    stateCode: "TX",
    medianHomePrice: 364_800,
    propertyTaxRate: 0.014,
    medianHouseholdIncome: 121_100,
  },
  "phoenix": {
    name: "Phoenix",
    state: "Arizona",
    stateCode: "AZ",
    medianHomePrice: 445_900,
    propertyTaxRate: 0.0048,
    medianHouseholdIncome: 112_400,
  },
  "tucson": {
    name: "Tucson",
    state: "Arizona",
    stateCode: "AZ",
    medianHomePrice: 340_900,
    propertyTaxRate: 0.0048,
    medianHouseholdIncome: 99_800,
  },
  "los-angeles": {
    name: "Los Angeles",
    state: "California",
    stateCode: "CA",
    medianHomePrice: 964_900,
    propertyTaxRate: 0.007,
    medianHouseholdIncome: 108_100,
  },
  "san-diego": {
    name: "San Diego",
    state: "California",
    stateCode: "CA",
    medianHomePrice: 934_200,
    propertyTaxRate: 0.007,
    medianHouseholdIncome: 130_900,
  },
  "san-francisco": {
    name: "San Francisco",
    state: "California",
    stateCode: "CA",
    medianHomePrice: 1_136_800,
    propertyTaxRate: 0.007,
    medianHouseholdIncome: 162_800,
  },
  "sacramento": {
    name: "Sacramento",
    state: "California",
    stateCode: "CA",
    medianHomePrice: 581_800,
    propertyTaxRate: 0.007,
    medianHouseholdIncome: 124_000,
  },
  "denver": {
    name: "Denver",
    state: "Colorado",
    stateCode: "CO",
    medianHomePrice: 566_500,
    propertyTaxRate: 0.005,
    medianHouseholdIncome: 144_000,
  },
  "chicago": {
    name: "Chicago",
    state: "Illinois",
    stateCode: "IL",
    medianHomePrice: 360_300,
    propertyTaxRate: 0.0188,
    medianHouseholdIncome: 121_500,
  },
  "atlanta": {
    name: "Atlanta",
    state: "Georgia",
    stateCode: "GA",
    medianHomePrice: 381_900,
    propertyTaxRate: 0.0079,
    medianHouseholdIncome: 117_800,
  },
  "miami": {
    name: "Miami",
    state: "Florida",
    stateCode: "FL",
    medianHomePrice: 477_800,
    propertyTaxRate: 0.0078,
    medianHouseholdIncome: 102_500,
  },
  "tampa": {
    name: "Tampa",
    state: "Florida",
    stateCode: "FL",
    medianHomePrice: 361_600,
    propertyTaxRate: 0.0078,
    medianHouseholdIncome: 104_700,
  },
  "orlando": {
    name: "Orlando",
    state: "Florida",
    stateCode: "FL",
    medianHomePrice: 386_900,
    propertyTaxRate: 0.0078,
    medianHouseholdIncome: 97_600,
  },
  "jacksonville": {
    name: "Jacksonville",
    state: "Florida",
    stateCode: "FL",
    medianHomePrice: 353_000,
    propertyTaxRate: 0.0078,
    medianHouseholdIncome: 108_700,
  },
  "charlotte": {
    name: "Charlotte",
    state: "North Carolina",
    stateCode: "NC",
    medianHomePrice: 388_700,
    propertyTaxRate: 0.0066,
    medianHouseholdIncome: 117_400,
  },
  "raleigh": {
    name: "Raleigh",
    state: "North Carolina",
    stateCode: "NC",
    medianHomePrice: 437_500,
    propertyTaxRate: 0.0066,
    medianHouseholdIncome: 132_300,
  },
  "nashville": {
    name: "Nashville",
    state: "Tennessee",
    stateCode: "TN",
    medianHomePrice: 455_400,
    propertyTaxRate: 0.0052,
    medianHouseholdIncome: 116_100,
  },
  "memphis": {
    name: "Memphis",
    state: "Tennessee",
    stateCode: "TN",
    medianHomePrice: 246_100,
    propertyTaxRate: 0.0052,
    medianHouseholdIncome: 75_800,
  },
  "las-vegas": {
    name: "Las Vegas",
    state: "Nevada",
    stateCode: "NV",
    medianHomePrice: 429_600,
    propertyTaxRate: 0.005,
    medianHouseholdIncome: 98_200,
  },
  "seattle": {
    name: "Seattle",
    state: "Washington",
    stateCode: "WA",
    medianHomePrice: 740_600,
    propertyTaxRate: 0.0075,
    medianHouseholdIncome: 164_400,
  },
  "portland": {
    name: "Portland",
    state: "Oregon",
    stateCode: "OR",
    medianHomePrice: 549_200,
    propertyTaxRate: 0.0081,
    medianHouseholdIncome: 128_300,
  },
  "minneapolis": {
    name: "Minneapolis",
    state: "Minnesota",
    stateCode: "MN",
    medianHomePrice: 394_700,
    propertyTaxRate: 0.01,
    medianHouseholdIncome: 131_500,
  },
  "columbus": {
    name: "Columbus",
    state: "Ohio",
    stateCode: "OH",
    medianHomePrice: 332_800,
    propertyTaxRate: 0.0136,
    medianHouseholdIncome: 111_500,
  },
  "indianapolis": {
    name: "Indianapolis",
    state: "Indiana",
    stateCode: "IN",
    medianHomePrice: 296_000,
    propertyTaxRate: 0.0076,
    medianHouseholdIncome: 110_300,
  },
  "detroit": {
    name: "Detroit",
    state: "Michigan",
    stateCode: "MI",
    medianHomePrice: 270_400,
    propertyTaxRate: 0.0119,
    medianHouseholdIncome: 104_800,
  },
  "philadelphia": {
    name: "Philadelphia",
    state: "Pennsylvania",
    stateCode: "PA",
    medianHomePrice: 392_300,
    propertyTaxRate: 0.0126,
    medianHouseholdIncome: 86_900,
  },
  "new-york-city": {
    name: "New York City",
    state: "New York",
    stateCode: "NY",
    medianHomePrice: 737_100,
    propertyTaxRate: 0.013,
    medianHouseholdIncome: 104_300,
  },
  "boston": {
    name: "Boston",
    state: "Massachusetts",
    stateCode: "MA",
    medianHomePrice: 742_300,
    propertyTaxRate: 0.01,
    medianHouseholdIncome: 164_600,
  },
  "baltimore": {
    name: "Baltimore",
    state: "Maryland",
    stateCode: "MD",
    medianHomePrice: 405_100,
    propertyTaxRate: 0.0092,
    medianHouseholdIncome: 134_000,
  },
  "louisville": {
    name: "Louisville",
    state: "Kentucky",
    stateCode: "KY",
    medianHomePrice: 282_000,
    propertyTaxRate: 0.0074,
    medianHouseholdIncome: 72_500,
  },
  "kansas-city": {
    name: "Kansas City",
    state: "Missouri",
    stateCode: "MO",
    medianHomePrice: 330_100,
    propertyTaxRate: 0.0089,
    medianHouseholdIncome: 78_000,
  },
  "salt-lake-city": {
    name: "Salt Lake City",
    state: "Utah",
    stateCode: "UT",
    medianHomePrice: 566_200,
    propertyTaxRate: 0.0048,
    medianHouseholdIncome: 126_100,
  },
  "richmond": {
    name: "Richmond",
    state: "Virginia",
    stateCode: "VA",
    medianHomePrice: 398_000,
    propertyTaxRate: 0.0078,
    medianHouseholdIncome: 113_500,
  },
  "albuquerque": {
    name: "Albuquerque",
    state: "New Mexico",
    stateCode: "NM",
    medianHomePrice: 352_700,
    propertyTaxRate: 0.0063,
    medianHouseholdIncome: 100_400,
  },
  "oklahoma-city": {
    name: "Oklahoma City",
    state: "Oklahoma",
    stateCode: "OK",
    medianHomePrice: 246_400,
    propertyTaxRate: 0.0079,
    medianHouseholdIncome: 97_300,
  },
  "milwaukee": {
    name: "Milwaukee",
    state: "Wisconsin",
    stateCode: "WI",
    medianHomePrice: 393_200,
    propertyTaxRate: 0.0132,
    medianHouseholdIncome: 108_400,
  },
  "montgomery": {
    name: "Montgomery",
    state: "Alabama",
    stateCode: "AL",
    medianHomePrice: 214_900,
    propertyTaxRate: 0.0037,
    medianHouseholdIncome: 88_800,
  },
  "huntsville": {
    name: "Huntsville",
    state: "Alabama",
    stateCode: "AL",
    medianHomePrice: 316_600,
    propertyTaxRate: 0.0037,
    medianHouseholdIncome: 115_100,
  },
  "mobile": {
    name: "Mobile",
    state: "Alabama",
    stateCode: "AL",
    medianHomePrice: 197_700,
    propertyTaxRate: 0.0037,
    medianHouseholdIncome: 83_300,
  },
  "tuscaloosa": {
    name: "Tuscaloosa",
    state: "Alabama",
    stateCode: "AL",
    medianHomePrice: 223_900,
    propertyTaxRate: 0.0037,
    medianHouseholdIncome: 93_000,
  },
  "fairbanks": {
    name: "Fairbanks",
    state: "Alaska",
    stateCode: "AK",
    medianHomePrice: 317_100,
    propertyTaxRate: 0.0094,
    medianHouseholdIncome: 116_300,
  },
  "juneau": {
    name: "Juneau",
    state: "Alaska",
    stateCode: "AK",
    medianHomePrice: 483_300,
    propertyTaxRate: 0.0094,
    medianHouseholdIncome: 111_600,
  },
  "sitka": {
    name: "Sitka",
    state: "Alaska",
    stateCode: "AK",
    medianHomePrice: 402_200,
    propertyTaxRate: 0.0094,
    medianHouseholdIncome: 111_600,
  },
  "ketchikan": {
    name: "Ketchikan",
    state: "Alaska",
    stateCode: "AK",
    medianHomePrice: 409_100,
    propertyTaxRate: 0.0094,
    medianHouseholdIncome: 111_600,
  },
  "fort-smith": {
    name: "Fort Smith",
    state: "Arkansas",
    stateCode: "AR",
    medianHomePrice: 204_800,
    propertyTaxRate: 0.0056,
    medianHouseholdIncome: 76_800,
  },
  "fayetteville": {
    name: "Fayetteville",
    state: "Arkansas",
    stateCode: "AR",
    medianHomePrice: 368_500,
    propertyTaxRate: 0.0056,
    medianHouseholdIncome: 106_900,
  },
  "springdale": {
    name: "Springdale",
    state: "Arkansas",
    stateCode: "AR",
    medianHomePrice: 368_500,
    propertyTaxRate: 0.0056,
    medianHouseholdIncome: 106_900,
  },
  "jonesboro": {
    name: "Jonesboro",
    state: "Arkansas",
    stateCode: "AR",
    medianHomePrice: 205_600,
    propertyTaxRate: 0.0056,
    medianHouseholdIncome: 75_600,
  },
  "new-haven": {
    name: "New Haven",
    state: "Connecticut",
    stateCode: "CT",
    medianHomePrice: 411_300,
    propertyTaxRate: 0.0154,
    medianHouseholdIncome: 123_200,
  },
  "hartford": {
    name: "Hartford",
    state: "Connecticut",
    stateCode: "CT",
    medianHomePrice: 404_900,
    propertyTaxRate: 0.0154,
    medianHouseholdIncome: 129_200,
  },
  "stamford": {
    name: "Stamford",
    state: "Connecticut",
    stateCode: "CT",
    medianHomePrice: 698_400,
    propertyTaxRate: 0.0154,
    medianHouseholdIncome: 156_800,
  },
  "waterbury": {
    name: "Waterbury",
    state: "Connecticut",
    stateCode: "CT",
    medianHomePrice: 453_300,
    propertyTaxRate: 0.0154,
    medianHouseholdIncome: 114_000,
  },
  "dover": {
    name: "Dover",
    state: "Delaware",
    stateCode: "DE",
    medianHomePrice: 374_700,
    propertyTaxRate: 0.0054,
    medianHouseholdIncome: 112_100,
  },
  "newark-de": {
    name: "Newark",
    state: "Delaware",
    stateCode: "DE",
    medianHomePrice: 410_200,
    propertyTaxRate: 0.0054,
    medianHouseholdIncome: 112_100,
  },
  "middletown": {
    name: "Middletown",
    state: "Delaware",
    stateCode: "DE",
    medianHomePrice: 410_200,
    propertyTaxRate: 0.0054,
    medianHouseholdIncome: 112_100,
  },
  "smyrna": {
    name: "Smyrna",
    state: "Delaware",
    stateCode: "DE",
    medianHomePrice: 410_200,
    propertyTaxRate: 0.0054,
    medianHouseholdIncome: 112_100,
  },
  "hilo": {
    name: "Hilo",
    state: "Hawaii",
    stateCode: "HI",
    medianHomePrice: 577_400,
    propertyTaxRate: 0.0029,
    medianHouseholdIncome: 121_400,
  },
  "kailua": {
    name: "Kailua",
    state: "Hawaii",
    stateCode: "HI",
    medianHomePrice: 833_900,
    propertyTaxRate: 0.0029,
    medianHouseholdIncome: 121_400,
  },
  "pearl-city": {
    name: "Pearl City",
    state: "Hawaii",
    stateCode: "HI",
    medianHomePrice: 833_900,
    propertyTaxRate: 0.0029,
    medianHouseholdIncome: 121_400,
  },
  "waipahu": {
    name: "Waipahu",
    state: "Hawaii",
    stateCode: "HI",
    medianHomePrice: 833_900,
    propertyTaxRate: 0.0029,
    medianHouseholdIncome: 121_400,
  },
  "meridian": {
    name: "Meridian",
    state: "Idaho",
    stateCode: "ID",
    medianHomePrice: 481_800,
    propertyTaxRate: 0.005,
    medianHouseholdIncome: 85_200,
  },
  "nampa": {
    name: "Nampa",
    state: "Idaho",
    stateCode: "ID",
    medianHomePrice: 481_800,
    propertyTaxRate: 0.005,
    medianHouseholdIncome: 85_200,
  },
  "idaho-falls": {
    name: "Idaho Falls",
    state: "Idaho",
    stateCode: "ID",
    medianHomePrice: 413_700,
    propertyTaxRate: 0.005,
    medianHouseholdIncome: 101_100,
  },
  "pocatello": {
    name: "Pocatello",
    state: "Idaho",
    stateCode: "ID",
    medianHomePrice: 355_700,
    propertyTaxRate: 0.005,
    medianHouseholdIncome: 100_800,
  },
  "cedar-rapids": {
    name: "Cedar Rapids",
    state: "Iowa",
    stateCode: "IA",
    medianHomePrice: 247_100,
    propertyTaxRate: 0.0133,
    medianHouseholdIncome: 105_300,
  },
  "davenport": {
    name: "Davenport",
    state: "Iowa",
    stateCode: "IA",
    medianHomePrice: 198_100,
    propertyTaxRate: 0.0133,
    medianHouseholdIncome: 95_500,
  },
  "sioux-city": {
    name: "Sioux City",
    state: "Iowa",
    stateCode: "IA",
    medianHomePrice: 228_400,
    propertyTaxRate: 0.0133,
    medianHouseholdIncome: 97_900,
  },
  "iowa-city": {
    name: "Iowa City",
    state: "Iowa",
    stateCode: "IA",
    medianHomePrice: 304_700,
    propertyTaxRate: 0.0133,
    medianHouseholdIncome: 121_400,
  },
  "overland-park": {
    name: "Overland Park",
    state: "Kansas",
    stateCode: "KS",
    medianHomePrice: 250_900,
    propertyTaxRate: 0.0121,
    medianHouseholdIncome: 86_900,
  },
  "topeka": {
    name: "Topeka",
    state: "Kansas",
    stateCode: "KS",
    medianHomePrice: 220_300,
    propertyTaxRate: 0.0121,
    medianHouseholdIncome: 98_800,
  },
  "olathe": {
    name: "Olathe",
    state: "Kansas",
    stateCode: "KS",
    medianHomePrice: 250_900,
    propertyTaxRate: 0.0121,
    medianHouseholdIncome: 86_900,
  },
  "lawrence": {
    name: "Lawrence",
    state: "Kansas",
    stateCode: "KS",
    medianHomePrice: 343_000,
    propertyTaxRate: 0.0121,
    medianHouseholdIncome: 110_400,
  },
  "baton-rouge": {
    name: "Baton Rouge",
    state: "Louisiana",
    stateCode: "LA",
    medianHomePrice: 249_600,
    propertyTaxRate: 0.0055,
    medianHouseholdIncome: 94_500,
  },
  "shreveport": {
    name: "Shreveport",
    state: "Louisiana",
    stateCode: "LA",
    medianHomePrice: 185_000,
    propertyTaxRate: 0.0055,
    medianHouseholdIncome: 79_200,
  },
  "lafayette": {
    name: "Lafayette",
    state: "Louisiana",
    stateCode: "LA",
    medianHomePrice: 202_300,
    propertyTaxRate: 0.0055,
    medianHouseholdIncome: 90_300,
  },
  "lake-charles": {
    name: "Lake Charles",
    state: "Louisiana",
    stateCode: "LA",
    medianHomePrice: 201_300,
    propertyTaxRate: 0.0055,
    medianHouseholdIncome: 93_000,
  },
  "lewiston": {
    name: "Lewiston",
    state: "Maine",
    stateCode: "ME",
    medianHomePrice: 337_600,
    propertyTaxRate: 0.0098,
    medianHouseholdIncome: 96_600,
  },
  "bangor": {
    name: "Bangor",
    state: "Maine",
    stateCode: "ME",
    medianHomePrice: 286_700,
    propertyTaxRate: 0.0098,
    medianHouseholdIncome: 106_500,
  },
  "south-portland": {
    name: "South Portland",
    state: "Maine",
    stateCode: "ME",
    medianHomePrice: 547_000,
    propertyTaxRate: 0.0098,
    medianHouseholdIncome: 139_100,
  },
  "auburn-me": {
    name: "Auburn",
    state: "Maine",
    stateCode: "ME",
    medianHomePrice: 337_600,
    propertyTaxRate: 0.0098,
    medianHouseholdIncome: 96_600,
  },
  "gulfport": {
    name: "Gulfport",
    state: "Mississippi",
    stateCode: "MS",
    medianHomePrice: 223_500,
    propertyTaxRate: 0.0058,
    medianHouseholdIncome: 83_100,
  },
  "southaven": {
    name: "Southaven",
    state: "Mississippi",
    stateCode: "MS",
    medianHomePrice: 196_300,
    propertyTaxRate: 0.0058,
    medianHouseholdIncome: 67_000,
  },
  "hattiesburg": {
    name: "Hattiesburg",
    state: "Mississippi",
    stateCode: "MS",
    medianHomePrice: 217_800,
    propertyTaxRate: 0.0058,
    medianHouseholdIncome: 79_800,
  },
  "biloxi": {
    name: "Biloxi",
    state: "Mississippi",
    stateCode: "MS",
    medianHomePrice: 223_500,
    propertyTaxRate: 0.0058,
    medianHouseholdIncome: 83_100,
  },
  "missoula": {
    name: "Missoula",
    state: "Montana",
    stateCode: "MT",
    medianHomePrice: 580_200,
    propertyTaxRate: 0.0061,
    medianHouseholdIncome: 110_100,
  },
  "great-falls": {
    name: "Great Falls",
    state: "Montana",
    stateCode: "MT",
    medianHomePrice: 344_100,
    propertyTaxRate: 0.0061,
    medianHouseholdIncome: 89_000,
  },
  "bozeman": {
    name: "Bozeman",
    state: "Montana",
    stateCode: "MT",
    medianHomePrice: 701_500,
    propertyTaxRate: 0.0061,
    medianHouseholdIncome: 130_200,
  },
  "butte": {
    name: "Butte",
    state: "Montana",
    stateCode: "MT",
    medianHomePrice: 288_800,
    propertyTaxRate: 0.0061,
    medianHouseholdIncome: 87_800,
  },
  "lincoln": {
    name: "Lincoln",
    state: "Nebraska",
    stateCode: "NE",
    medianHomePrice: 304_500,
    propertyTaxRate: 0.0144,
    medianHouseholdIncome: 106_600,
  },
  "bellevue": {
    name: "Bellevue",
    state: "Nebraska",
    stateCode: "NE",
    medianHomePrice: 282_800,
    propertyTaxRate: 0.0144,
    medianHouseholdIncome: 90_700,
  },
  "grand-island": {
    name: "Grand Island",
    state: "Nebraska",
    stateCode: "NE",
    medianHomePrice: 259_500,
    propertyTaxRate: 0.0144,
    medianHouseholdIncome: 90_700,
  },
  "kearney": {
    name: "Kearney",
    state: "Nebraska",
    stateCode: "NE",
    medianHomePrice: 302_300,
    propertyTaxRate: 0.0144,
    medianHouseholdIncome: 90_700,
  },
  "nashua": {
    name: "Nashua",
    state: "New Hampshire",
    stateCode: "NH",
    medianHomePrice: 529_000,
    propertyTaxRate: 0.015,
    medianHouseholdIncome: 147_600,
  },
  "concord": {
    name: "Concord",
    state: "New Hampshire",
    stateCode: "NH",
    medianHomePrice: 498_900,
    propertyTaxRate: 0.015,
    medianHouseholdIncome: 119_200,
  },
  "derry": {
    name: "Derry",
    state: "New Hampshire",
    stateCode: "NH",
    medianHomePrice: 521_200,
    propertyTaxRate: 0.015,
    medianHouseholdIncome: 119_200,
  },
  "dover-nh": {
    name: "Dover",
    state: "New Hampshire",
    stateCode: "NH",
    medianHomePrice: 521_200,
    propertyTaxRate: 0.015,
    medianHouseholdIncome: 119_200,
  },
  "jersey-city": {
    name: "Jersey City",
    state: "New Jersey",
    stateCode: "NJ",
    medianHomePrice: 584_100,
    propertyTaxRate: 0.0188,
    medianHouseholdIncome: 138_400,
  },
  "paterson": {
    name: "Paterson",
    state: "New Jersey",
    stateCode: "NJ",
    medianHomePrice: 584_100,
    propertyTaxRate: 0.0188,
    medianHouseholdIncome: 133_150,
  },
  "elizabeth": {
    name: "Elizabeth",
    state: "New Jersey",
    stateCode: "NJ",
    medianHomePrice: 584_100,
    propertyTaxRate: 0.0188,
    medianHouseholdIncome: 133_150,
  },
  "trenton": {
    name: "Trenton",
    state: "New Jersey",
    stateCode: "NJ",
    medianHomePrice: 451_000,
    propertyTaxRate: 0.0188,
    medianHouseholdIncome: 139_800,
  },
  "bismarck": {
    name: "Bismarck",
    state: "North Dakota",
    stateCode: "ND",
    medianHomePrice: 361_900,
    propertyTaxRate: 0.0092,
    medianHouseholdIncome: 113_000,
  },
  "grand-forks": {
    name: "Grand Forks",
    state: "North Dakota",
    stateCode: "ND",
    medianHomePrice: 283_200,
    propertyTaxRate: 0.0092,
    medianHouseholdIncome: 105_300,
  },
  "minot": {
    name: "Minot",
    state: "North Dakota",
    stateCode: "ND",
    medianHomePrice: 272_100,
    propertyTaxRate: 0.0092,
    medianHouseholdIncome: 105_300,
  },
  "west-fargo": {
    name: "West Fargo",
    state: "North Dakota",
    stateCode: "ND",
    medianHomePrice: 330_500,
    propertyTaxRate: 0.0092,
    medianHouseholdIncome: 105_300,
  },
  "cranston": {
    name: "Cranston",
    state: "Rhode Island",
    stateCode: "RI",
    medianHomePrice: 515_300,
    propertyTaxRate: 0.0112,
    medianHouseholdIncome: 133_350,
  },
  "warwick": {
    name: "Warwick",
    state: "Rhode Island",
    stateCode: "RI",
    medianHomePrice: 529_800,
    propertyTaxRate: 0.0112,
    medianHouseholdIncome: 133_350,
  },
  "pawtucket": {
    name: "Pawtucket",
    state: "Rhode Island",
    stateCode: "RI",
    medianHomePrice: 515_300,
    propertyTaxRate: 0.0112,
    medianHouseholdIncome: 133_350,
  },
  "east-providence": {
    name: "East Providence",
    state: "Rhode Island",
    stateCode: "RI",
    medianHomePrice: 529_800,
    propertyTaxRate: 0.0112,
    medianHouseholdIncome: 133_350,
  },
  "charleston": {
    name: "Charleston",
    state: "South Carolina",
    stateCode: "SC",
    medianHomePrice: 435_600,
    propertyTaxRate: 0.0049,
    medianHouseholdIncome: 117_500,
  },
  "north-charleston": {
    name: "North Charleston",
    state: "South Carolina",
    stateCode: "SC",
    medianHomePrice: 435_600,
    propertyTaxRate: 0.0049,
    medianHouseholdIncome: 117_500,
  },
  "greenville-sc": {
    name: "Greenville",
    state: "South Carolina",
    stateCode: "SC",
    medianHomePrice: 315_000,
    propertyTaxRate: 0.0049,
    medianHouseholdIncome: 95_100,
  },
  "spartanburg": {
    name: "Spartanburg",
    state: "South Carolina",
    stateCode: "SC",
    medianHomePrice: 278_700,
    propertyTaxRate: 0.0049,
    medianHouseholdIncome: 91_200,
  },
  "rapid-city": {
    name: "Rapid City",
    state: "South Dakota",
    stateCode: "SD",
    medianHomePrice: 376_400,
    propertyTaxRate: 0.01,
    medianHouseholdIncome: 101_300,
  },
  "aberdeen-sd": {
    name: "Aberdeen",
    state: "South Dakota",
    stateCode: "SD",
    medianHomePrice: 244_900,
    propertyTaxRate: 0.01,
    medianHouseholdIncome: 97_950,
  },
  "brookings": {
    name: "Brookings",
    state: "South Dakota",
    stateCode: "SD",
    medianHomePrice: 330_200,
    propertyTaxRate: 0.01,
    medianHouseholdIncome: 97_950,
  },
  "watertown-sd": {
    name: "Watertown",
    state: "South Dakota",
    stateCode: "SD",
    medianHomePrice: 344_600,
    propertyTaxRate: 0.01,
    medianHouseholdIncome: 97_950,
  },
  "south-burlington": {
    name: "South Burlington",
    state: "Vermont",
    stateCode: "VT",
    medianHomePrice: 478_100,
    propertyTaxRate: 0.0151,
    medianHouseholdIncome: 123_400,
  },
  "rutland": {
    name: "Rutland",
    state: "Vermont",
    stateCode: "VT",
    medianHomePrice: 321_900,
    propertyTaxRate: 0.0151,
    medianHouseholdIncome: 102_000,
  },
  "barre": {
    name: "Barre",
    state: "Vermont",
    stateCode: "VT",
    medianHomePrice: 403_200,
    propertyTaxRate: 0.0151,
    medianHouseholdIncome: 102_000,
  },
  "montpelier": {
    name: "Montpelier",
    state: "Vermont",
    stateCode: "VT",
    medianHomePrice: 406_000,
    propertyTaxRate: 0.0151,
    medianHouseholdIncome: 102_000,
  },
  "huntington-wv": {
    name: "Huntington",
    state: "West Virginia",
    stateCode: "WV",
    medianHomePrice: 167_800,
    propertyTaxRate: 0.0051,
    medianHouseholdIncome: 74_200,
  },
  "parkersburg": {
    name: "Parkersburg",
    state: "West Virginia",
    stateCode: "WV",
    medianHomePrice: 170_900,
    propertyTaxRate: 0.0051,
    medianHouseholdIncome: 74_100,
  },
  "morgantown": {
    name: "Morgantown",
    state: "West Virginia",
    stateCode: "WV",
    medianHomePrice: 228_100,
    propertyTaxRate: 0.0051,
    medianHouseholdIncome: 103_000,
  },
  "wheeling": {
    name: "Wheeling",
    state: "West Virginia",
    stateCode: "WV",
    medianHomePrice: 143_300,
    propertyTaxRate: 0.0051,
    medianHouseholdIncome: 74_200,
  },
  "casper": {
    name: "Casper",
    state: "Wyoming",
    stateCode: "WY",
    medianHomePrice: 315_900,
    propertyTaxRate: 0.0053,
    medianHouseholdIncome: 99_500,
  },
  "laramie": {
    name: "Laramie",
    state: "Wyoming",
    stateCode: "WY",
    medianHomePrice: 380_500,
    propertyTaxRate: 0.0053,
    medianHouseholdIncome: 100_200,
  },
  "gillette": {
    name: "Gillette",
    state: "Wyoming",
    stateCode: "WY",
    medianHomePrice: 339_800,
    propertyTaxRate: 0.0053,
    medianHouseholdIncome: 100_200,
  },
  "rock-springs": {
    name: "Rock Springs",
    state: "Wyoming",
    stateCode: "WY",
    medianHomePrice: 293_800,
    propertyTaxRate: 0.0053,
    medianHouseholdIncome: 100_200,
  },
  "aurora": {
    name: "Aurora",
    state: "Colorado",
    stateCode: "CO",
    medianHomePrice: 566_500,
    propertyTaxRate: 0.005,
    medianHouseholdIncome: 144_000,
  },
  "fort-collins": {
    name: "Fort Collins",
    state: "Colorado",
    stateCode: "CO",
    medianHomePrice: 554_600,
    propertyTaxRate: 0.005,
    medianHouseholdIncome: 130_400,
  },
  "aurora-il": {
    name: "Aurora",
    state: "Illinois",
    stateCode: "IL",
    medianHomePrice: 299_900,
    propertyTaxRate: 0.0188,
    medianHouseholdIncome: 90_900,
  },
  "naperville": {
    name: "Naperville",
    state: "Illinois",
    stateCode: "IL",
    medianHomePrice: 360_300,
    propertyTaxRate: 0.0188,
    medianHouseholdIncome: 121_500,
  },
  "rockford": {
    name: "Rockford",
    state: "Illinois",
    stateCode: "IL",
    medianHomePrice: 224_400,
    propertyTaxRate: 0.0188,
    medianHouseholdIncome: 89_400,
  },
  "st-louis": {
    name: "St. Louis",
    state: "Missouri",
    stateCode: "MO",
    medianHomePrice: 277_400,
    propertyTaxRate: 0.0089,
    medianHouseholdIncome: 78_000,
  },
  "springfield-mo": {
    name: "Springfield",
    state: "Missouri",
    stateCode: "MO",
    medianHomePrice: 273_400,
    propertyTaxRate: 0.0089,
    medianHouseholdIncome: 91_400,
  },
  "columbia-mo": {
    name: "Columbia",
    state: "Missouri",
    stateCode: "MO",
    medianHomePrice: 323_000,
    propertyTaxRate: 0.0089,
    medianHouseholdIncome: 119_200,
  },
  "henderson": {
    name: "Henderson",
    state: "Nevada",
    stateCode: "NV",
    medianHomePrice: 429_600,
    propertyTaxRate: 0.005,
    medianHouseholdIncome: 98_200,
  },
  "reno": {
    name: "Reno",
    state: "Nevada",
    stateCode: "NV",
    medianHomePrice: 573_900,
    propertyTaxRate: 0.005,
    medianHouseholdIncome: 116_800,
  },
  "north-las-vegas": {
    name: "North Las Vegas",
    state: "Nevada",
    stateCode: "NV",
    medianHomePrice: 429_600,
    propertyTaxRate: 0.005,
    medianHouseholdIncome: 98_200,
  },
  "buffalo": {
    name: "Buffalo",
    state: "New York",
    stateCode: "NY",
    medianHomePrice: 292_900,
    propertyTaxRate: 0.013,
    medianHouseholdIncome: 101_500,
  },
  "rochester": {
    name: "Rochester",
    state: "New York",
    stateCode: "NY",
    medianHomePrice: 289_000,
    propertyTaxRate: 0.013,
    medianHouseholdIncome: 107_000,
  },
  "yonkers": {
    name: "Yonkers",
    state: "New York",
    stateCode: "NY",
    medianHomePrice: 527_300,
    propertyTaxRate: 0.013,
    medianHouseholdIncome: 94_100,
  },
  "cincinnati": {
    name: "Cincinnati",
    state: "Ohio",
    stateCode: "OH",
    medianHomePrice: 311_100,
    propertyTaxRate: 0.0136,
    medianHouseholdIncome: 87_650,
  },
  "cleveland": {
    name: "Cleveland",
    state: "Ohio",
    stateCode: "OH",
    medianHomePrice: 254_500,
    propertyTaxRate: 0.0136,
    medianHouseholdIncome: 105_000,
  },
  "dayton-oh": {
    name: "Dayton",
    state: "Ohio",
    stateCode: "OH",
    medianHomePrice: 249_900,
    propertyTaxRate: 0.0136,
    medianHouseholdIncome: 103_000,
  },
  "pittsburgh": {
    name: "Pittsburgh",
    state: "Pennsylvania",
    stateCode: "PA",
    medianHomePrice: 231_700,
    propertyTaxRate: 0.0126,
    medianHouseholdIncome: 110_400,
  },
  "allentown": {
    name: "Allentown",
    state: "Pennsylvania",
    stateCode: "PA",
    medianHomePrice: 368_600,
    propertyTaxRate: 0.0126,
    medianHouseholdIncome: 104_400,
  },
  "erie": {
    name: "Erie",
    state: "Pennsylvania",
    stateCode: "PA",
    medianHomePrice: 226_800,
    propertyTaxRate: 0.0126,
    medianHouseholdIncome: 88_600,
  },
  "knoxville": {
    name: "Knoxville",
    state: "Tennessee",
    stateCode: "TN",
    medianHomePrice: 367_900,
    propertyTaxRate: 0.0052,
    medianHouseholdIncome: 103_700,
  },
  "chattanooga": {
    name: "Chattanooga",
    state: "Tennessee",
    stateCode: "TN",
    medianHomePrice: 326_000,
    propertyTaxRate: 0.0052,
    medianHouseholdIncome: 75_800,
  },
  "provo": {
    name: "Provo",
    state: "Utah",
    stateCode: "UT",
    medianHomePrice: 544_900,
    propertyTaxRate: 0.0048,
    medianHouseholdIncome: 119_200,
  },
  "west-valley-city": {
    name: "West Valley City",
    state: "Utah",
    stateCode: "UT",
    medianHomePrice: 539_900,
    propertyTaxRate: 0.0048,
    medianHouseholdIncome: 98_300,
  },
  "west-jordan": {
    name: "West Jordan",
    state: "Utah",
    stateCode: "UT",
    medianHomePrice: 539_900,
    propertyTaxRate: 0.0048,
    medianHouseholdIncome: 98_300,
  },
  "virginia-beach": {
    name: "Virginia Beach",
    state: "Virginia",
    stateCode: "VA",
    medianHomePrice: 375_700,
    propertyTaxRate: 0.0078,
    medianHouseholdIncome: 86_300,
  },
  "norfolk": {
    name: "Norfolk",
    state: "Virginia",
    stateCode: "VA",
    medianHomePrice: 375_700,
    propertyTaxRate: 0.0078,
    medianHouseholdIncome: 86_300,
  },
  "chesapeake": {
    name: "Chesapeake",
    state: "Virginia",
    stateCode: "VA",
    medianHomePrice: 375_700,
    propertyTaxRate: 0.0078,
    medianHouseholdIncome: 86_300,
  },
  "spokane": {
    name: "Spokane",
    state: "Washington",
    stateCode: "WA",
    medianHomePrice: 425_000,
    propertyTaxRate: 0.0075,
    medianHouseholdIncome: 110_500,
  },
  "tacoma": {
    name: "Tacoma",
    state: "Washington",
    stateCode: "WA",
    medianHomePrice: 740_600,
    propertyTaxRate: 0.0075,
    medianHouseholdIncome: 164_400,
  },
  "bellevue-wa": {
    name: "Bellevue",
    state: "Washington",
    stateCode: "WA",
    medianHomePrice: 740_600,
    propertyTaxRate: 0.0075,
    medianHouseholdIncome: 164_400,
  },
  "madison": {
    name: "Madison",
    state: "Wisconsin",
    stateCode: "WI",
    medianHomePrice: 452_900,
    propertyTaxRate: 0.0132,
    medianHouseholdIncome: 135_300,
  },
  "green-bay": {
    name: "Green Bay",
    state: "Wisconsin",
    stateCode: "WI",
    medianHomePrice: 351_900,
    propertyTaxRate: 0.0132,
    medianHouseholdIncome: 106_300,
  },
  "kenosha": {
    name: "Kenosha",
    state: "Wisconsin",
    stateCode: "WI",
    medianHomePrice: 343_800,
    propertyTaxRate: 0.0132,
    medianHouseholdIncome: 117_300,
  },
  "san-jose": {
    name: "San Jose",
    state: "California",
    stateCode: "CA",
    medianHomePrice: 1_559_200,
    propertyTaxRate: 0.007,
    medianHouseholdIncome: 205_500,
  },
  "fresno": {
    name: "Fresno",
    state: "California",
    stateCode: "CA",
    medianHomePrice: 409_800,
    propertyTaxRate: 0.007,
    medianHouseholdIncome: 91_300,
  },
  "long-beach": {
    name: "Long Beach",
    state: "California",
    stateCode: "CA",
    medianHomePrice: 964_900,
    propertyTaxRate: 0.007,
    medianHouseholdIncome: 108_100,
  },
  "tucson-extra": {
    name: "Mesa",
    state: "Arizona",
    stateCode: "AZ",
    medianHomePrice: 445_900,
    propertyTaxRate: 0.0048,
    medianHouseholdIncome: 112_400,
  },
  "chandler": {
    name: "Chandler",
    state: "Arizona",
    stateCode: "AZ",
    medianHomePrice: 445_900,
    propertyTaxRate: 0.0048,
    medianHouseholdIncome: 112_400,
  },
  "scottsdale": {
    name: "Scottsdale",
    state: "Arizona",
    stateCode: "AZ",
    medianHomePrice: 421_400,
    propertyTaxRate: 0.0048,
    medianHouseholdIncome: 79_600,
  },
  "savannah": {
    name: "Savannah",
    state: "Georgia",
    stateCode: "GA",
    medianHomePrice: 345_400,
    propertyTaxRate: 0.0079,
    medianHouseholdIncome: 107_300,
  },
  "columbus-ga": {
    name: "Columbus",
    state: "Georgia",
    stateCode: "GA",
    medianHomePrice: 209_700,
    propertyTaxRate: 0.0079,
    medianHouseholdIncome: 72_500,
  },
  "augusta": {
    name: "Augusta",
    state: "Georgia",
    stateCode: "GA",
    medianHomePrice: 253_300,
    propertyTaxRate: 0.0079,
    medianHouseholdIncome: 90_400,
  },
  "fort-lauderdale": {
    name: "Fort Lauderdale",
    state: "Florida",
    stateCode: "FL",
    medianHomePrice: 477_800,
    propertyTaxRate: 0.0078,
    medianHouseholdIncome: 102_500,
  },
  "st-petersburg": {
    name: "St. Petersburg",
    state: "Florida",
    stateCode: "FL",
    medianHomePrice: 361_600,
    propertyTaxRate: 0.0078,
    medianHouseholdIncome: 104_700,
  },
  "hialeah": {
    name: "Hialeah",
    state: "Florida",
    stateCode: "FL",
    medianHomePrice: 378_200,
    propertyTaxRate: 0.0078,
    medianHouseholdIncome: 83_950,
  },
  "greensboro": {
    name: "Greensboro",
    state: "North Carolina",
    stateCode: "NC",
    medianHomePrice: 265_200,
    propertyTaxRate: 0.0066,
    medianHouseholdIncome: 91_500,
  },
  "durham-nc": {
    name: "Durham",
    state: "North Carolina",
    stateCode: "NC",
    medianHomePrice: 411_300,
    propertyTaxRate: 0.0066,
    medianHouseholdIncome: 129_900,
  },
  "winston-salem": {
    name: "Winston-Salem",
    state: "North Carolina",
    stateCode: "NC",
    medianHomePrice: 282_300,
    propertyTaxRate: 0.0066,
    medianHouseholdIncome: 96_700,
  },
};

export const CITY_SLUGS = Object.keys(CITY_DATA) as (keyof typeof CITY_DATA)[];

// Required annual income to afford the median home in a city.
// Formula: (medianHomePrice * 0.75 * 0.065 / 12) / 0.28 * 12
// = 75% loan (25% down) at 6.5% rate, front-end DTI 28%
// Note: uses city property tax rate for the PITI housing payment estimate.
export function calcRequiredIncome(city: CityData): number {
  const loanAmount = city.medianHomePrice * 0.75;
  const monthlyRate = 0.065 / 12;
  const months = 360;
  const monthlyPI =
    loanAmount * (monthlyRate * Math.pow(1 + monthlyRate, months)) /
    (Math.pow(1 + monthlyRate, months) - 1);
  const monthlyTax = (city.medianHomePrice * city.propertyTaxRate) / 12;
  const monthlyInsurance = (city.medianHomePrice * 0.005) / 12;
  const totalMonthlyHousing = monthlyPI + monthlyTax + monthlyInsurance;
  // Reverse the 28% front-end DTI: monthly = income/12 * 0.28
  const requiredMonthly = totalMonthlyHousing / 0.28;
  return Math.round(requiredMonthly * 12);
}
