// ============================================================
// Top 181 US home-buying metros — 2024 data
// Sources: NAR, Zillow, Tax Foundation, Census ACS
// ============================================================

export interface CityData {
  name: string;
  state: string;
  stateCode: string;
  medianHomePrice: number;
  propertyTaxRate: number;   // annual, decimal (e.g. 0.0172 = 1.72%)
  medianHouseholdIncome: number;
}

export const CITY_DATA: Record<string, CityData> = {
  "houston": {
    name: "Houston",
    state: "Texas",
    stateCode: "TX",
    medianHomePrice: 310000,
    propertyTaxRate: 0.0223,
    medianHouseholdIncome: 62000,
  },
  "san-antonio": {
    name: "San Antonio",
    state: "Texas",
    stateCode: "TX",
    medianHomePrice: 280000,
    propertyTaxRate: 0.021,
    medianHouseholdIncome: 58000,
  },
  "dallas": {
    name: "Dallas",
    state: "Texas",
    stateCode: "TX",
    medianHomePrice: 355000,
    propertyTaxRate: 0.023,
    medianHouseholdIncome: 68000,
  },
  "austin": {
    name: "Austin",
    state: "Texas",
    stateCode: "TX",
    medianHomePrice: 490000,
    propertyTaxRate: 0.0197,
    medianHouseholdIncome: 82000,
  },
  "fort-worth": {
    name: "Fort Worth",
    state: "Texas",
    stateCode: "TX",
    medianHomePrice: 310000,
    propertyTaxRate: 0.0225,
    medianHouseholdIncome: 64000,
  },
  "phoenix": {
    name: "Phoenix",
    state: "Arizona",
    stateCode: "AZ",
    medianHomePrice: 420000,
    propertyTaxRate: 0.007,
    medianHouseholdIncome: 67000,
  },
  "tucson": {
    name: "Tucson",
    state: "Arizona",
    stateCode: "AZ",
    medianHomePrice: 295000,
    propertyTaxRate: 0.0072,
    medianHouseholdIncome: 52000,
  },
  "los-angeles": {
    name: "Los Angeles",
    state: "California",
    stateCode: "CA",
    medianHomePrice: 895000,
    propertyTaxRate: 0.0074,
    medianHouseholdIncome: 76000,
  },
  "san-diego": {
    name: "San Diego",
    state: "California",
    stateCode: "CA",
    medianHomePrice: 870000,
    propertyTaxRate: 0.0076,
    medianHouseholdIncome: 88000,
  },
  "san-francisco": {
    name: "San Francisco",
    state: "California",
    stateCode: "CA",
    medianHomePrice: 1200000,
    propertyTaxRate: 0.0065,
    medianHouseholdIncome: 130000,
  },
  "sacramento": {
    name: "Sacramento",
    state: "California",
    stateCode: "CA",
    medianHomePrice: 550000,
    propertyTaxRate: 0.0078,
    medianHouseholdIncome: 73000,
  },
  "denver": {
    name: "Denver",
    state: "Colorado",
    stateCode: "CO",
    medianHomePrice: 570000,
    propertyTaxRate: 0.0055,
    medianHouseholdIncome: 78000,
  },
  "chicago": {
    name: "Chicago",
    state: "Illinois",
    stateCode: "IL",
    medianHomePrice: 295000,
    propertyTaxRate: 0.0208,
    medianHouseholdIncome: 65000,
  },
  "atlanta": {
    name: "Atlanta",
    state: "Georgia",
    stateCode: "GA",
    medianHomePrice: 390000,
    propertyTaxRate: 0.01,
    medianHouseholdIncome: 72000,
  },
  "miami": {
    name: "Miami",
    state: "Florida",
    stateCode: "FL",
    medianHomePrice: 600000,
    propertyTaxRate: 0.0102,
    medianHouseholdIncome: 59000,
  },
  "tampa": {
    name: "Tampa",
    state: "Florida",
    stateCode: "FL",
    medianHomePrice: 390000,
    propertyTaxRate: 0.0095,
    medianHouseholdIncome: 62000,
  },
  "orlando": {
    name: "Orlando",
    state: "Florida",
    stateCode: "FL",
    medianHomePrice: 380000,
    propertyTaxRate: 0.0088,
    medianHouseholdIncome: 61000,
  },
  "jacksonville": {
    name: "Jacksonville",
    state: "Florida",
    stateCode: "FL",
    medianHomePrice: 310000,
    propertyTaxRate: 0.0085,
    medianHouseholdIncome: 60000,
  },
  "charlotte": {
    name: "Charlotte",
    state: "North Carolina",
    stateCode: "NC",
    medianHomePrice: 390000,
    propertyTaxRate: 0.0087,
    medianHouseholdIncome: 72000,
  },
  "raleigh": {
    name: "Raleigh",
    state: "North Carolina",
    stateCode: "NC",
    medianHomePrice: 420000,
    propertyTaxRate: 0.0083,
    medianHouseholdIncome: 78000,
  },
  "nashville": {
    name: "Nashville",
    state: "Tennessee",
    stateCode: "TN",
    medianHomePrice: 450000,
    propertyTaxRate: 0.0073,
    medianHouseholdIncome: 72000,
  },
  "memphis": {
    name: "Memphis",
    state: "Tennessee",
    stateCode: "TN",
    medianHomePrice: 200000,
    propertyTaxRate: 0.0077,
    medianHouseholdIncome: 48000,
  },
  "las-vegas": {
    name: "Las Vegas",
    state: "Nevada",
    stateCode: "NV",
    medianHomePrice: 440000,
    propertyTaxRate: 0.0065,
    medianHouseholdIncome: 63000,
  },
  "seattle": {
    name: "Seattle",
    state: "Washington",
    stateCode: "WA",
    medianHomePrice: 780000,
    propertyTaxRate: 0.0092,
    medianHouseholdIncome: 110000,
  },
  "portland": {
    name: "Portland",
    state: "Oregon",
    stateCode: "OR",
    medianHomePrice: 510000,
    propertyTaxRate: 0.0091,
    medianHouseholdIncome: 76000,
  },
  "minneapolis": {
    name: "Minneapolis",
    state: "Minnesota",
    stateCode: "MN",
    medianHomePrice: 355000,
    propertyTaxRate: 0.012,
    medianHouseholdIncome: 78000,
  },
  "columbus": {
    name: "Columbus",
    state: "Ohio",
    stateCode: "OH",
    medianHomePrice: 265000,
    propertyTaxRate: 0.0185,
    medianHouseholdIncome: 63000,
  },
  "indianapolis": {
    name: "Indianapolis",
    state: "Indiana",
    stateCode: "IN",
    medianHomePrice: 265000,
    propertyTaxRate: 0.0108,
    medianHouseholdIncome: 58000,
  },
  "detroit": {
    name: "Detroit",
    state: "Michigan",
    stateCode: "MI",
    medianHomePrice: 185000,
    propertyTaxRate: 0.0244,
    medianHouseholdIncome: 38000,
  },
  "philadelphia": {
    name: "Philadelphia",
    state: "Pennsylvania",
    stateCode: "PA",
    medianHomePrice: 265000,
    propertyTaxRate: 0.013,
    medianHouseholdIncome: 55000,
  },
  "new-york-city": {
    name: "New York City",
    state: "New York",
    stateCode: "NY",
    medianHomePrice: 750000,
    propertyTaxRate: 0.0088,
    medianHouseholdIncome: 70000,
  },
  "boston": {
    name: "Boston",
    state: "Massachusetts",
    stateCode: "MA",
    medianHomePrice: 750000,
    propertyTaxRate: 0.0102,
    medianHouseholdIncome: 98000,
  },
  "baltimore": {
    name: "Baltimore",
    state: "Maryland",
    stateCode: "MD",
    medianHomePrice: 310000,
    propertyTaxRate: 0.0122,
    medianHouseholdIncome: 58000,
  },
  "louisville": {
    name: "Louisville",
    state: "Kentucky",
    stateCode: "KY",
    medianHomePrice: 245000,
    propertyTaxRate: 0.009,
    medianHouseholdIncome: 58000,
  },
  "kansas-city": {
    name: "Kansas City",
    state: "Missouri",
    stateCode: "MO",
    medianHomePrice: 255000,
    propertyTaxRate: 0.0122,
    medianHouseholdIncome: 62000,
  },
  "salt-lake-city": {
    name: "Salt Lake City",
    state: "Utah",
    stateCode: "UT",
    medianHomePrice: 530000,
    propertyTaxRate: 0.0068,
    medianHouseholdIncome: 80000,
  },
  "richmond": {
    name: "Richmond",
    state: "Virginia",
    stateCode: "VA",
    medianHomePrice: 350000,
    propertyTaxRate: 0.012,
    medianHouseholdIncome: 67000,
  },
  "albuquerque": {
    name: "Albuquerque",
    state: "New Mexico",
    stateCode: "NM",
    medianHomePrice: 310000,
    propertyTaxRate: 0.0072,
    medianHouseholdIncome: 57000,
  },
  "oklahoma-city": {
    name: "Oklahoma City",
    state: "Oklahoma",
    stateCode: "OK",
    medianHomePrice: 215000,
    propertyTaxRate: 0.0115,
    medianHouseholdIncome: 58000,
  },
  "milwaukee": {
    name: "Milwaukee",
    state: "Wisconsin",
    stateCode: "WI",
    medianHomePrice: 225000,
    propertyTaxRate: 0.0217,
    medianHouseholdIncome: 52000,
  },
  "montgomery": {
    name: "Montgomery",
    state: "Alabama",
    stateCode: "AL",
    medianHomePrice: 185000,
    propertyTaxRate: 0.0043,
    medianHouseholdIncome: 48000,
  },
  "huntsville": {
    name: "Huntsville",
    state: "Alabama",
    stateCode: "AL",
    medianHomePrice: 285000,
    propertyTaxRate: 0.004,
    medianHouseholdIncome: 68000,
  },
  "mobile": {
    name: "Mobile",
    state: "Alabama",
    stateCode: "AL",
    medianHomePrice: 195000,
    propertyTaxRate: 0.0045,
    medianHouseholdIncome: 46000,
  },
  "tuscaloosa": {
    name: "Tuscaloosa",
    state: "Alabama",
    stateCode: "AL",
    medianHomePrice: 225000,
    propertyTaxRate: 0.0044,
    medianHouseholdIncome: 50000,
  },
  "fairbanks": {
    name: "Fairbanks",
    state: "Alaska",
    stateCode: "AK",
    medianHomePrice: 285000,
    propertyTaxRate: 0.012,
    medianHouseholdIncome: 72000,
  },
  "juneau": {
    name: "Juneau",
    state: "Alaska",
    stateCode: "AK",
    medianHomePrice: 380000,
    propertyTaxRate: 0.01,
    medianHouseholdIncome: 86000,
  },
  "sitka": {
    name: "Sitka",
    state: "Alaska",
    stateCode: "AK",
    medianHomePrice: 350000,
    propertyTaxRate: 0.009,
    medianHouseholdIncome: 75000,
  },
  "ketchikan": {
    name: "Ketchikan",
    state: "Alaska",
    stateCode: "AK",
    medianHomePrice: 340000,
    propertyTaxRate: 0.0105,
    medianHouseholdIncome: 70000,
  },
  "fort-smith": {
    name: "Fort Smith",
    state: "Arkansas",
    stateCode: "AR",
    medianHomePrice: 175000,
    propertyTaxRate: 0.0061,
    medianHouseholdIncome: 48000,
  },
  "fayetteville": {
    name: "Fayetteville",
    state: "Arkansas",
    stateCode: "AR",
    medianHomePrice: 295000,
    propertyTaxRate: 0.0064,
    medianHouseholdIncome: 62000,
  },
  "springdale": {
    name: "Springdale",
    state: "Arkansas",
    stateCode: "AR",
    medianHomePrice: 255000,
    propertyTaxRate: 0.0062,
    medianHouseholdIncome: 58000,
  },
  "jonesboro": {
    name: "Jonesboro",
    state: "Arkansas",
    stateCode: "AR",
    medianHomePrice: 195000,
    propertyTaxRate: 0.006,
    medianHouseholdIncome: 52000,
  },
  "new-haven": {
    name: "New Haven",
    state: "Connecticut",
    stateCode: "CT",
    medianHomePrice: 310000,
    propertyTaxRate: 0.0202,
    medianHouseholdIncome: 54000,
  },
  "hartford": {
    name: "Hartford",
    state: "Connecticut",
    stateCode: "CT",
    medianHomePrice: 225000,
    propertyTaxRate: 0.0216,
    medianHouseholdIncome: 49000,
  },
  "stamford": {
    name: "Stamford",
    state: "Connecticut",
    stateCode: "CT",
    medianHomePrice: 695000,
    propertyTaxRate: 0.0167,
    medianHouseholdIncome: 102000,
  },
  "waterbury": {
    name: "Waterbury",
    state: "Connecticut",
    stateCode: "CT",
    medianHomePrice: 240000,
    propertyTaxRate: 0.021,
    medianHouseholdIncome: 50000,
  },
  "dover": {
    name: "Dover",
    state: "Delaware",
    stateCode: "DE",
    medianHomePrice: 265000,
    propertyTaxRate: 0.0055,
    medianHouseholdIncome: 58000,
  },
  "newark-de": {
    name: "Newark",
    state: "Delaware",
    stateCode: "DE",
    medianHomePrice: 310000,
    propertyTaxRate: 0.0058,
    medianHouseholdIncome: 64000,
  },
  "middletown": {
    name: "Middletown",
    state: "Delaware",
    stateCode: "DE",
    medianHomePrice: 360000,
    propertyTaxRate: 0.0053,
    medianHouseholdIncome: 82000,
  },
  "smyrna": {
    name: "Smyrna",
    state: "Delaware",
    stateCode: "DE",
    medianHomePrice: 295000,
    propertyTaxRate: 0.0054,
    medianHouseholdIncome: 65000,
  },
  "hilo": {
    name: "Hilo",
    state: "Hawaii",
    stateCode: "HI",
    medianHomePrice: 415000,
    propertyTaxRate: 0.0035,
    medianHouseholdIncome: 62000,
  },
  "kailua": {
    name: "Kailua",
    state: "Hawaii",
    stateCode: "HI",
    medianHomePrice: 1100000,
    propertyTaxRate: 0.0027,
    medianHouseholdIncome: 115000,
  },
  "pearl-city": {
    name: "Pearl City",
    state: "Hawaii",
    stateCode: "HI",
    medianHomePrice: 780000,
    propertyTaxRate: 0.0029,
    medianHouseholdIncome: 92000,
  },
  "waipahu": {
    name: "Waipahu",
    state: "Hawaii",
    stateCode: "HI",
    medianHomePrice: 720000,
    propertyTaxRate: 0.003,
    medianHouseholdIncome: 85000,
  },
  "meridian": {
    name: "Meridian",
    state: "Idaho",
    stateCode: "ID",
    medianHomePrice: 480000,
    propertyTaxRate: 0.007,
    medianHouseholdIncome: 82000,
  },
  "nampa": {
    name: "Nampa",
    state: "Idaho",
    stateCode: "ID",
    medianHomePrice: 380000,
    propertyTaxRate: 0.0068,
    medianHouseholdIncome: 62000,
  },
  "idaho-falls": {
    name: "Idaho Falls",
    state: "Idaho",
    stateCode: "ID",
    medianHomePrice: 320000,
    propertyTaxRate: 0.0065,
    medianHouseholdIncome: 60000,
  },
  "pocatello": {
    name: "Pocatello",
    state: "Idaho",
    stateCode: "ID",
    medianHomePrice: 270000,
    propertyTaxRate: 0.0066,
    medianHouseholdIncome: 52000,
  },
  "cedar-rapids": {
    name: "Cedar Rapids",
    state: "Iowa",
    stateCode: "IA",
    medianHomePrice: 195000,
    propertyTaxRate: 0.015,
    medianHouseholdIncome: 60000,
  },
  "davenport": {
    name: "Davenport",
    state: "Iowa",
    stateCode: "IA",
    medianHomePrice: 185000,
    propertyTaxRate: 0.0153,
    medianHouseholdIncome: 56000,
  },
  "sioux-city": {
    name: "Sioux City",
    state: "Iowa",
    stateCode: "IA",
    medianHomePrice: 175000,
    propertyTaxRate: 0.0144,
    medianHouseholdIncome: 55000,
  },
  "iowa-city": {
    name: "Iowa City",
    state: "Iowa",
    stateCode: "IA",
    medianHomePrice: 265000,
    propertyTaxRate: 0.0145,
    medianHouseholdIncome: 68000,
  },
  "overland-park": {
    name: "Overland Park",
    state: "Kansas",
    stateCode: "KS",
    medianHomePrice: 380000,
    propertyTaxRate: 0.0121,
    medianHouseholdIncome: 90000,
  },
  "topeka": {
    name: "Topeka",
    state: "Kansas",
    stateCode: "KS",
    medianHomePrice: 165000,
    propertyTaxRate: 0.0128,
    medianHouseholdIncome: 52000,
  },
  "olathe": {
    name: "Olathe",
    state: "Kansas",
    stateCode: "KS",
    medianHomePrice: 350000,
    propertyTaxRate: 0.0124,
    medianHouseholdIncome: 88000,
  },
  "lawrence": {
    name: "Lawrence",
    state: "Kansas",
    stateCode: "KS",
    medianHomePrice: 265000,
    propertyTaxRate: 0.0125,
    medianHouseholdIncome: 58000,
  },
  "baton-rouge": {
    name: "Baton Rouge",
    state: "Louisiana",
    stateCode: "LA",
    medianHomePrice: 225000,
    propertyTaxRate: 0.0048,
    medianHouseholdIncome: 56000,
  },
  "shreveport": {
    name: "Shreveport",
    state: "Louisiana",
    stateCode: "LA",
    medianHomePrice: 175000,
    propertyTaxRate: 0.0044,
    medianHouseholdIncome: 48000,
  },
  "lafayette": {
    name: "Lafayette",
    state: "Louisiana",
    stateCode: "LA",
    medianHomePrice: 210000,
    propertyTaxRate: 0.0046,
    medianHouseholdIncome: 55000,
  },
  "lake-charles": {
    name: "Lake Charles",
    state: "Louisiana",
    stateCode: "LA",
    medianHomePrice: 185000,
    propertyTaxRate: 0.0045,
    medianHouseholdIncome: 52000,
  },
  "lewiston": {
    name: "Lewiston",
    state: "Maine",
    stateCode: "ME",
    medianHomePrice: 235000,
    propertyTaxRate: 0.0115,
    medianHouseholdIncome: 48000,
  },
  "bangor": {
    name: "Bangor",
    state: "Maine",
    stateCode: "ME",
    medianHomePrice: 265000,
    propertyTaxRate: 0.012,
    medianHouseholdIncome: 52000,
  },
  "south-portland": {
    name: "South Portland",
    state: "Maine",
    stateCode: "ME",
    medianHomePrice: 420000,
    propertyTaxRate: 0.0108,
    medianHouseholdIncome: 70000,
  },
  "auburn-me": {
    name: "Auburn",
    state: "Maine",
    stateCode: "ME",
    medianHomePrice: 215000,
    propertyTaxRate: 0.0112,
    medianHouseholdIncome: 50000,
  },
  "gulfport": {
    name: "Gulfport",
    state: "Mississippi",
    stateCode: "MS",
    medianHomePrice: 195000,
    propertyTaxRate: 0.0058,
    medianHouseholdIncome: 50000,
  },
  "southaven": {
    name: "Southaven",
    state: "Mississippi",
    stateCode: "MS",
    medianHomePrice: 225000,
    propertyTaxRate: 0.0055,
    medianHouseholdIncome: 68000,
  },
  "hattiesburg": {
    name: "Hattiesburg",
    state: "Mississippi",
    stateCode: "MS",
    medianHomePrice: 180000,
    propertyTaxRate: 0.006,
    medianHouseholdIncome: 46000,
  },
  "biloxi": {
    name: "Biloxi",
    state: "Mississippi",
    stateCode: "MS",
    medianHomePrice: 215000,
    propertyTaxRate: 0.0057,
    medianHouseholdIncome: 52000,
  },
  "missoula": {
    name: "Missoula",
    state: "Montana",
    stateCode: "MT",
    medianHomePrice: 460000,
    propertyTaxRate: 0.0085,
    medianHouseholdIncome: 62000,
  },
  "great-falls": {
    name: "Great Falls",
    state: "Montana",
    stateCode: "MT",
    medianHomePrice: 285000,
    propertyTaxRate: 0.008,
    medianHouseholdIncome: 56000,
  },
  "bozeman": {
    name: "Bozeman",
    state: "Montana",
    stateCode: "MT",
    medianHomePrice: 650000,
    propertyTaxRate: 0.0078,
    medianHouseholdIncome: 72000,
  },
  "butte": {
    name: "Butte",
    state: "Montana",
    stateCode: "MT",
    medianHomePrice: 225000,
    propertyTaxRate: 0.0082,
    medianHouseholdIncome: 52000,
  },
  "lincoln": {
    name: "Lincoln",
    state: "Nebraska",
    stateCode: "NE",
    medianHomePrice: 245000,
    propertyTaxRate: 0.0165,
    medianHouseholdIncome: 65000,
  },
  "bellevue": {
    name: "Bellevue",
    state: "Nebraska",
    stateCode: "NE",
    medianHomePrice: 265000,
    propertyTaxRate: 0.017,
    medianHouseholdIncome: 72000,
  },
  "grand-island": {
    name: "Grand Island",
    state: "Nebraska",
    stateCode: "NE",
    medianHomePrice: 195000,
    propertyTaxRate: 0.016,
    medianHouseholdIncome: 58000,
  },
  "kearney": {
    name: "Kearney",
    state: "Nebraska",
    stateCode: "NE",
    medianHomePrice: 210000,
    propertyTaxRate: 0.0162,
    medianHouseholdIncome: 60000,
  },
  "nashua": {
    name: "Nashua",
    state: "New Hampshire",
    stateCode: "NH",
    medianHomePrice: 410000,
    propertyTaxRate: 0.02,
    medianHouseholdIncome: 80000,
  },
  "concord": {
    name: "Concord",
    state: "New Hampshire",
    stateCode: "NH",
    medianHomePrice: 355000,
    propertyTaxRate: 0.0208,
    medianHouseholdIncome: 68000,
  },
  "derry": {
    name: "Derry",
    state: "New Hampshire",
    stateCode: "NH",
    medianHomePrice: 390000,
    propertyTaxRate: 0.0205,
    medianHouseholdIncome: 78000,
  },
  "dover-nh": {
    name: "Dover",
    state: "New Hampshire",
    stateCode: "NH",
    medianHomePrice: 365000,
    propertyTaxRate: 0.0202,
    medianHouseholdIncome: 70000,
  },
  "jersey-city": {
    name: "Jersey City",
    state: "New Jersey",
    stateCode: "NJ",
    medianHomePrice: 650000,
    propertyTaxRate: 0.0197,
    medianHouseholdIncome: 82000,
  },
  "paterson": {
    name: "Paterson",
    state: "New Jersey",
    stateCode: "NJ",
    medianHomePrice: 350000,
    propertyTaxRate: 0.0233,
    medianHouseholdIncome: 52000,
  },
  "elizabeth": {
    name: "Elizabeth",
    state: "New Jersey",
    stateCode: "NJ",
    medianHomePrice: 425000,
    propertyTaxRate: 0.023,
    medianHouseholdIncome: 58000,
  },
  "trenton": {
    name: "Trenton",
    state: "New Jersey",
    stateCode: "NJ",
    medianHomePrice: 225000,
    propertyTaxRate: 0.0255,
    medianHouseholdIncome: 46000,
  },
  "bismarck": {
    name: "Bismarck",
    state: "North Dakota",
    stateCode: "ND",
    medianHomePrice: 285000,
    propertyTaxRate: 0.01,
    medianHouseholdIncome: 68000,
  },
  "grand-forks": {
    name: "Grand Forks",
    state: "North Dakota",
    stateCode: "ND",
    medianHomePrice: 245000,
    propertyTaxRate: 0.0105,
    medianHouseholdIncome: 60000,
  },
  "minot": {
    name: "Minot",
    state: "North Dakota",
    stateCode: "ND",
    medianHomePrice: 255000,
    propertyTaxRate: 0.0102,
    medianHouseholdIncome: 62000,
  },
  "west-fargo": {
    name: "West Fargo",
    state: "North Dakota",
    stateCode: "ND",
    medianHomePrice: 310000,
    propertyTaxRate: 0.0101,
    medianHouseholdIncome: 76000,
  },
  "cranston": {
    name: "Cranston",
    state: "Rhode Island",
    stateCode: "RI",
    medianHomePrice: 390000,
    propertyTaxRate: 0.014,
    medianHouseholdIncome: 68000,
  },
  "warwick": {
    name: "Warwick",
    state: "Rhode Island",
    stateCode: "RI",
    medianHomePrice: 370000,
    propertyTaxRate: 0.0145,
    medianHouseholdIncome: 72000,
  },
  "pawtucket": {
    name: "Pawtucket",
    state: "Rhode Island",
    stateCode: "RI",
    medianHomePrice: 320000,
    propertyTaxRate: 0.0168,
    medianHouseholdIncome: 52000,
  },
  "east-providence": {
    name: "East Providence",
    state: "Rhode Island",
    stateCode: "RI",
    medianHomePrice: 340000,
    propertyTaxRate: 0.0155,
    medianHouseholdIncome: 60000,
  },
  "charleston": {
    name: "Charleston",
    state: "South Carolina",
    stateCode: "SC",
    medianHomePrice: 520000,
    propertyTaxRate: 0.005,
    medianHouseholdIncome: 78000,
  },
  "north-charleston": {
    name: "North Charleston",
    state: "South Carolina",
    stateCode: "SC",
    medianHomePrice: 310000,
    propertyTaxRate: 0.0054,
    medianHouseholdIncome: 58000,
  },
  "greenville-sc": {
    name: "Greenville",
    state: "South Carolina",
    stateCode: "SC",
    medianHomePrice: 340000,
    propertyTaxRate: 0.0052,
    medianHouseholdIncome: 72000,
  },
  "spartanburg": {
    name: "Spartanburg",
    state: "South Carolina",
    stateCode: "SC",
    medianHomePrice: 265000,
    propertyTaxRate: 0.0055,
    medianHouseholdIncome: 58000,
  },
  "rapid-city": {
    name: "Rapid City",
    state: "South Dakota",
    stateCode: "SD",
    medianHomePrice: 310000,
    propertyTaxRate: 0.011,
    medianHouseholdIncome: 64000,
  },
  "aberdeen-sd": {
    name: "Aberdeen",
    state: "South Dakota",
    stateCode: "SD",
    medianHomePrice: 195000,
    propertyTaxRate: 0.0115,
    medianHouseholdIncome: 58000,
  },
  "brookings": {
    name: "Brookings",
    state: "South Dakota",
    stateCode: "SD",
    medianHomePrice: 235000,
    propertyTaxRate: 0.0112,
    medianHouseholdIncome: 58000,
  },
  "watertown-sd": {
    name: "Watertown",
    state: "South Dakota",
    stateCode: "SD",
    medianHomePrice: 195000,
    propertyTaxRate: 0.0113,
    medianHouseholdIncome: 58000,
  },
  "south-burlington": {
    name: "South Burlington",
    state: "Vermont",
    stateCode: "VT",
    medianHomePrice: 490000,
    propertyTaxRate: 0.018,
    medianHouseholdIncome: 82000,
  },
  "rutland": {
    name: "Rutland",
    state: "Vermont",
    stateCode: "VT",
    medianHomePrice: 245000,
    propertyTaxRate: 0.0192,
    medianHouseholdIncome: 52000,
  },
  "barre": {
    name: "Barre",
    state: "Vermont",
    stateCode: "VT",
    medianHomePrice: 210000,
    propertyTaxRate: 0.0197,
    medianHouseholdIncome: 50000,
  },
  "montpelier": {
    name: "Montpelier",
    state: "Vermont",
    stateCode: "VT",
    medianHomePrice: 310000,
    propertyTaxRate: 0.0185,
    medianHouseholdIncome: 62000,
  },
  "huntington-wv": {
    name: "Huntington",
    state: "West Virginia",
    stateCode: "WV",
    medianHomePrice: 145000,
    propertyTaxRate: 0.0055,
    medianHouseholdIncome: 46000,
  },
  "parkersburg": {
    name: "Parkersburg",
    state: "West Virginia",
    stateCode: "WV",
    medianHomePrice: 155000,
    propertyTaxRate: 0.0058,
    medianHouseholdIncome: 48000,
  },
  "morgantown": {
    name: "Morgantown",
    state: "West Virginia",
    stateCode: "WV",
    medianHomePrice: 245000,
    propertyTaxRate: 0.0052,
    medianHouseholdIncome: 58000,
  },
  "wheeling": {
    name: "Wheeling",
    state: "West Virginia",
    stateCode: "WV",
    medianHomePrice: 130000,
    propertyTaxRate: 0.006,
    medianHouseholdIncome: 44000,
  },
  "casper": {
    name: "Casper",
    state: "Wyoming",
    stateCode: "WY",
    medianHomePrice: 295000,
    propertyTaxRate: 0.0065,
    medianHouseholdIncome: 65000,
  },
  "laramie": {
    name: "Laramie",
    state: "Wyoming",
    stateCode: "WY",
    medianHomePrice: 310000,
    propertyTaxRate: 0.0062,
    medianHouseholdIncome: 58000,
  },
  "gillette": {
    name: "Gillette",
    state: "Wyoming",
    stateCode: "WY",
    medianHomePrice: 285000,
    propertyTaxRate: 0.006,
    medianHouseholdIncome: 72000,
  },
  "rock-springs": {
    name: "Rock Springs",
    state: "Wyoming",
    stateCode: "WY",
    medianHomePrice: 265000,
    propertyTaxRate: 0.0063,
    medianHouseholdIncome: 68000,
  },
  "aurora": {
    name: "Aurora",
    state: "Colorado",
    stateCode: "CO",
    medianHomePrice: 480000,
    propertyTaxRate: 0.0056,
    medianHouseholdIncome: 70000,
  },
  "fort-collins": {
    name: "Fort Collins",
    state: "Colorado",
    stateCode: "CO",
    medianHomePrice: 530000,
    propertyTaxRate: 0.0052,
    medianHouseholdIncome: 78000,
  },
  "aurora-il": {
    name: "Aurora",
    state: "Illinois",
    stateCode: "IL",
    medianHomePrice: 280000,
    propertyTaxRate: 0.0212,
    medianHouseholdIncome: 68000,
  },
  "naperville": {
    name: "Naperville",
    state: "Illinois",
    stateCode: "IL",
    medianHomePrice: 440000,
    propertyTaxRate: 0.0205,
    medianHouseholdIncome: 105000,
  },
  "rockford": {
    name: "Rockford",
    state: "Illinois",
    stateCode: "IL",
    medianHomePrice: 155000,
    propertyTaxRate: 0.0245,
    medianHouseholdIncome: 48000,
  },
  "st-louis": {
    name: "St. Louis",
    state: "Missouri",
    stateCode: "MO",
    medianHomePrice: 185000,
    propertyTaxRate: 0.0135,
    medianHouseholdIncome: 52000,
  },
  "springfield-mo": {
    name: "Springfield",
    state: "Missouri",
    stateCode: "MO",
    medianHomePrice: 195000,
    propertyTaxRate: 0.0118,
    medianHouseholdIncome: 50000,
  },
  "columbia-mo": {
    name: "Columbia",
    state: "Missouri",
    stateCode: "MO",
    medianHomePrice: 245000,
    propertyTaxRate: 0.011,
    medianHouseholdIncome: 58000,
  },
  "henderson": {
    name: "Henderson",
    state: "Nevada",
    stateCode: "NV",
    medianHomePrice: 460000,
    propertyTaxRate: 0.0062,
    medianHouseholdIncome: 72000,
  },
  "reno": {
    name: "Reno",
    state: "Nevada",
    stateCode: "NV",
    medianHomePrice: 480000,
    propertyTaxRate: 0.0067,
    medianHouseholdIncome: 68000,
  },
  "north-las-vegas": {
    name: "North Las Vegas",
    state: "Nevada",
    stateCode: "NV",
    medianHomePrice: 390000,
    propertyTaxRate: 0.0064,
    medianHouseholdIncome: 60000,
  },
  "buffalo": {
    name: "Buffalo",
    state: "New York",
    stateCode: "NY",
    medianHomePrice: 195000,
    propertyTaxRate: 0.0206,
    medianHouseholdIncome: 48000,
  },
  "rochester": {
    name: "Rochester",
    state: "New York",
    stateCode: "NY",
    medianHomePrice: 195000,
    propertyTaxRate: 0.029,
    medianHouseholdIncome: 46000,
  },
  "yonkers": {
    name: "Yonkers",
    state: "New York",
    stateCode: "NY",
    medianHomePrice: 480000,
    propertyTaxRate: 0.0182,
    medianHouseholdIncome: 62000,
  },
  "cincinnati": {
    name: "Cincinnati",
    state: "Ohio",
    stateCode: "OH",
    medianHomePrice: 240000,
    propertyTaxRate: 0.016,
    medianHouseholdIncome: 58000,
  },
  "cleveland": {
    name: "Cleveland",
    state: "Ohio",
    stateCode: "OH",
    medianHomePrice: 155000,
    propertyTaxRate: 0.0206,
    medianHouseholdIncome: 38000,
  },
  "dayton-oh": {
    name: "Dayton",
    state: "Ohio",
    stateCode: "OH",
    medianHomePrice: 155000,
    propertyTaxRate: 0.0188,
    medianHouseholdIncome: 44000,
  },
  "pittsburgh": {
    name: "Pittsburgh",
    state: "Pennsylvania",
    stateCode: "PA",
    medianHomePrice: 215000,
    propertyTaxRate: 0.016,
    medianHouseholdIncome: 52000,
  },
  "allentown": {
    name: "Allentown",
    state: "Pennsylvania",
    stateCode: "PA",
    medianHomePrice: 215000,
    propertyTaxRate: 0.021,
    medianHouseholdIncome: 48000,
  },
  "erie": {
    name: "Erie",
    state: "Pennsylvania",
    stateCode: "PA",
    medianHomePrice: 155000,
    propertyTaxRate: 0.0175,
    medianHouseholdIncome: 44000,
  },
  "knoxville": {
    name: "Knoxville",
    state: "Tennessee",
    stateCode: "TN",
    medianHomePrice: 310000,
    propertyTaxRate: 0.0074,
    medianHouseholdIncome: 58000,
  },
  "chattanooga": {
    name: "Chattanooga",
    state: "Tennessee",
    stateCode: "TN",
    medianHomePrice: 320000,
    propertyTaxRate: 0.007,
    medianHouseholdIncome: 60000,
  },
  "provo": {
    name: "Provo",
    state: "Utah",
    stateCode: "UT",
    medianHomePrice: 445000,
    propertyTaxRate: 0.0065,
    medianHouseholdIncome: 72000,
  },
  "west-valley-city": {
    name: "West Valley City",
    state: "Utah",
    stateCode: "UT",
    medianHomePrice: 410000,
    propertyTaxRate: 0.0067,
    medianHouseholdIncome: 65000,
  },
  "west-jordan": {
    name: "West Jordan",
    state: "Utah",
    stateCode: "UT",
    medianHomePrice: 430000,
    propertyTaxRate: 0.0066,
    medianHouseholdIncome: 72000,
  },
  "virginia-beach": {
    name: "Virginia Beach",
    state: "Virginia",
    stateCode: "VA",
    medianHomePrice: 365000,
    propertyTaxRate: 0.0099,
    medianHouseholdIncome: 78000,
  },
  "norfolk": {
    name: "Norfolk",
    state: "Virginia",
    stateCode: "VA",
    medianHomePrice: 295000,
    propertyTaxRate: 0.0111,
    medianHouseholdIncome: 58000,
  },
  "chesapeake": {
    name: "Chesapeake",
    state: "Virginia",
    stateCode: "VA",
    medianHomePrice: 375000,
    propertyTaxRate: 0.0091,
    medianHouseholdIncome: 80000,
  },
  "spokane": {
    name: "Spokane",
    state: "Washington",
    stateCode: "WA",
    medianHomePrice: 320000,
    propertyTaxRate: 0.011,
    medianHouseholdIncome: 56000,
  },
  "tacoma": {
    name: "Tacoma",
    state: "Washington",
    stateCode: "WA",
    medianHomePrice: 450000,
    propertyTaxRate: 0.0108,
    medianHouseholdIncome: 68000,
  },
  "bellevue-wa": {
    name: "Bellevue",
    state: "Washington",
    stateCode: "WA",
    medianHomePrice: 1100000,
    propertyTaxRate: 0.009,
    medianHouseholdIncome: 140000,
  },
  "madison": {
    name: "Madison",
    state: "Wisconsin",
    stateCode: "WI",
    medianHomePrice: 360000,
    propertyTaxRate: 0.0202,
    medianHouseholdIncome: 72000,
  },
  "green-bay": {
    name: "Green Bay",
    state: "Wisconsin",
    stateCode: "WI",
    medianHomePrice: 255000,
    propertyTaxRate: 0.0215,
    medianHouseholdIncome: 58000,
  },
  "kenosha": {
    name: "Kenosha",
    state: "Wisconsin",
    stateCode: "WI",
    medianHomePrice: 240000,
    propertyTaxRate: 0.021,
    medianHouseholdIncome: 60000,
  },
  "san-jose": {
    name: "San Jose",
    state: "California",
    stateCode: "CA",
    medianHomePrice: 1350000,
    propertyTaxRate: 0.0073,
    medianHouseholdIncome: 135000,
  },
  "fresno": {
    name: "Fresno",
    state: "California",
    stateCode: "CA",
    medianHomePrice: 370000,
    propertyTaxRate: 0.0077,
    medianHouseholdIncome: 55000,
  },
  "long-beach": {
    name: "Long Beach",
    state: "California",
    stateCode: "CA",
    medianHomePrice: 760000,
    propertyTaxRate: 0.0075,
    medianHouseholdIncome: 72000,
  },
  "tucson-extra": {
    name: "Mesa",
    state: "Arizona",
    stateCode: "AZ",
    medianHomePrice: 390000,
    propertyTaxRate: 0.0068,
    medianHouseholdIncome: 65000,
  },
  "chandler": {
    name: "Chandler",
    state: "Arizona",
    stateCode: "AZ",
    medianHomePrice: 440000,
    propertyTaxRate: 0.0067,
    medianHouseholdIncome: 82000,
  },
  "scottsdale": {
    name: "Scottsdale",
    state: "Arizona",
    stateCode: "AZ",
    medianHomePrice: 720000,
    propertyTaxRate: 0.0065,
    medianHouseholdIncome: 102000,
  },
  "savannah": {
    name: "Savannah",
    state: "Georgia",
    stateCode: "GA",
    medianHomePrice: 320000,
    propertyTaxRate: 0.0098,
    medianHouseholdIncome: 58000,
  },
  "columbus-ga": {
    name: "Columbus",
    state: "Georgia",
    stateCode: "GA",
    medianHomePrice: 215000,
    propertyTaxRate: 0.0092,
    medianHouseholdIncome: 52000,
  },
  "augusta": {
    name: "Augusta",
    state: "Georgia",
    stateCode: "GA",
    medianHomePrice: 195000,
    propertyTaxRate: 0.0095,
    medianHouseholdIncome: 50000,
  },
  "fort-lauderdale": {
    name: "Fort Lauderdale",
    state: "Florida",
    stateCode: "FL",
    medianHomePrice: 530000,
    propertyTaxRate: 0.0098,
    medianHouseholdIncome: 68000,
  },
  "st-petersburg": {
    name: "St. Petersburg",
    state: "Florida",
    stateCode: "FL",
    medianHomePrice: 360000,
    propertyTaxRate: 0.0092,
    medianHouseholdIncome: 62000,
  },
  "hialeah": {
    name: "Hialeah",
    state: "Florida",
    stateCode: "FL",
    medianHomePrice: 450000,
    propertyTaxRate: 0.01,
    medianHouseholdIncome: 52000,
  },
  "greensboro": {
    name: "Greensboro",
    state: "North Carolina",
    stateCode: "NC",
    medianHomePrice: 265000,
    propertyTaxRate: 0.0092,
    medianHouseholdIncome: 56000,
  },
  "durham-nc": {
    name: "Durham",
    state: "North Carolina",
    stateCode: "NC",
    medianHomePrice: 380000,
    propertyTaxRate: 0.0085,
    medianHouseholdIncome: 68000,
  },
  "winston-salem": {
    name: "Winston-Salem",
    state: "North Carolina",
    stateCode: "NC",
    medianHomePrice: 255000,
    propertyTaxRate: 0.009,
    medianHouseholdIncome: 54000,
  },
};

export const CITY_SLUGS = Object.keys(CITY_DATA) as (keyof typeof CITY_DATA)[];

// Required annual income to afford the median home in a city.
// Formula: (medianHomePrice * 0.75 * 0.065 / 12) / 0.28 * 12
// = 75% loan (25% down) at 6.5% rate, front-end DTI 28%
// Note: uses city property tax rate for the PITI housing payment estimate.
export function calcRequiredIncome(city: CityData): number {
  const loanAmount = city.medianHomePrice * 0.75;
  const monthlyRate = 0.065 / 12;
  const months = 360;
  const monthlyPI =
    loanAmount * (monthlyRate * Math.pow(1 + monthlyRate, months)) /
    (Math.pow(1 + monthlyRate, months) - 1);
  const monthlyTax = (city.medianHomePrice * city.propertyTaxRate) / 12;
  const monthlyInsurance = (city.medianHomePrice * 0.005) / 12;
  const totalMonthlyHousing = monthlyPI + monthlyTax + monthlyInsurance;
  // Reverse the 28% front-end DTI: monthly = income/12 * 0.28
  const requiredMonthly = totalMonthlyHousing / 0.28;
  return Math.round(requiredMonthly * 12);
}
